feat: use starknetid.js
starknet-id/app.starknet.id pull request #182
Opened 2023-04-12 15:59 UTC by irisdv

Closes #162 
- updates `hooks/naming.ts` file to use starknetid.js package (some functions will need to be updated when dapp uses starknet.js v5)
- update `get_verifier_data` calls to use `getVerifierData` function in `clickableTwitterIcon`, `clickableGithubIcon` and `clickableDiscordIcon`
- move `naming` tests to starknetid.js package repo

2023-04-12 16:31 UTC, fricoben requested changes
Quelques commentaires, j'aimerais bien en profiter pour améliorer les fonctions d'encoding

2023-04-12 16:31 UTC, fricoben commented on components/identities/actions/clickable/clickableDiscordIcon.tsx
> +      ?.getVerifierData(parseInt(tokenId), "discord")
Parseint obligatoire ici ?

2023-04-12 16:31 UTC, fricoben commented on components/identities/actions/subdomainModal.tsx
> +  const encodedSubdomain: string = utils.encode(subdomain ?? "").toString(10);
obliger de garder `?? ""` ? Tu peux peut etre le gérer dans `encode`

2023-04-12 16:31 UTC, fricoben commented on components/identities/identitiesActions.tsx
> +// import { useEncodedSeveral } from "../../hooks/naming";
A delete ?

2023-04-12 16:31 UTC, fricoben commented on hooks/naming.ts
> +        .catch(() => {
j'ai mis l'erreur dans `AddressData`, tu peux peut etre changer le type, faire un `DomainData` et rajouter l'erreur ?

2023-04-12 16:31 UTC, fricoben commented on components/identities/identitiesActions.tsx
>      getDomainWithoutStark(identity ? identity.domain : "").split(".") ?? []
Je trouve que nos fonctions d'encoding n'abstract pas assez de choses, qu'en penses tu ? ici tu encodes `iris.starknetid.stark` par exemple c'est un peu une galère de lui envoyer le bon argument. 

Idéalement il faudrait faire les fonctions d'encoding tel que elle voit si ça finit par .stark, elle vire, elle voit si c'est un subdomain ou non et elle fait en fonction. 

Après il faudrait bien la tester ! à faire dans le repo du package npm du coup je pense.

2023-04-12 16:31 UTC, fricoben commented on components/identities/identitiesActions.tsx
>      getDomainWithoutStark(identity ? identity.domain : "").split(".") ?? []
ça transformerait ça 

```ts
utils.encodeSeveral(getDomainWithoutStark(identity ? identity.domain : "").split(".") ?? [])
```

en ça 

```ts
utils.encode(identity?.domain )
```

que ce soit définit ou non, que ce soit un subdomain ou non ...

2023-04-12 16:31 UTC, fricoben commented on context/StarknetIdJsProvider.tsx
> +export const StarknetIdJsProvider = ({ children }: { children: any }) => {
`any` à bannir :) + à mettre dans un type à part en haut du style type `StarknetIdJsProviderProps`

`React Node` surement comme type non ?

2023-04-12 16:31 UTC, fricoben commented on hooks/naming.ts
> +    ? utils.encodeDomain(domain).map((elem) => new BN(elem.toString())) // remove when dapp uses starknet.js v5
je ne comprend pas ce que tu fais là peux tu m'expliquer stp

2023-04-12 16:31 UTC, fricoben commented on hooks/useStarknetIdJs.tsx
> +  };
ce composant est vrmt nécéssaire ?

2023-04-12 16:38 UTC, irisdv commented on components/identities/actions/clickable/clickableDiscordIcon.tsx
> +      ?.getVerifierData(parseInt(tokenId), "discord")
le tokenId qu'on reçoit est une string, dans le package j'avais considéré que tokenId est un number. Sinon je peux modifier le package pour que le tokenId puisse être un number ou une string ?

2023-04-12 16:48 UTC, irisdv commented on components/identities/identitiesActions.tsx
>      getDomainWithoutStark(identity ? identity.domain : "").split(".") ?? []
Actuellement dans le package on a : `function encodeDomain(domain: string): bigint[] {}`
où domain peut se terminer en .stark ou non et qui gère les subdomains et renvoie une erreur si c'est vide. Je pourrais la modifier pour renvoyer un `[]` si jamais domain est vide.

ici, `encodeSeveral` ça renvoie un `string[]`. Soit on recrée une fonction équivalente qui renvoie un string[] au lieu d'un bigint[], soit on gère la conversion directement dans identitiesActions ligne 44-46:

```
  encodedDomains.forEach((domain) => {
    callDataEncodedDomain.push(domain);
  });
```

2023-04-12 16:50 UTC, irisdv commented on hooks/naming.ts
> +    ? utils.encodeDomain(domain).map((elem) => new BN(elem.toString())) // remove when dapp uses starknet.js v5
comme `encodeDomain` renvoie un `bigint[]` je map l'array retourné pour en faire des `BN` comme la version actuelle de starknet.js attends un `BN[]`

2023-04-12 16:56 UTC, irisdv commented on hooks/useStarknetIdJs.tsx
> +  };
c'est vrai qu'on pourrait directement utiliser `const { starknetIdNavigator } = useContext(StarknetIdJsContext);`

2023-04-12 18:11 UTC, irisdv commented on components/identities/actions/subdomainModal.tsx
> +  const encodedSubdomain: string = utils.encode(subdomain ?? "").toString(10);
Yes je peux le gérer dans `encode`

2023-04-13 11:03 UTC, fricoben commented on hooks/useStarknetIdJs.tsx
> +  };
Go alors

2023-04-13 11:12 UTC, fricoben commented on components/identities/identitiesActions.tsx
>      getDomainWithoutStark(identity ? identity.domain : "").split(".") ?? []
Quand je dis gère les .stark ça veut dire que la fonction les retirent si ils sont là. 

en gros un truc qui ferait ça 

```ts
function removeStarkSuffix(input: string): string {
  const suffix = '.stark';

  if (input.endsWith(suffix)) {
    return input.slice(0, -suffix.length);
  }

  return input;
}
```

c'est la fonction `getWithoutStark` que tu mettrait aussi dans encode. Actuellement en fait la fonction encode aussi `.stark`. 

De meme pour les subdomains ça n'encode pas bien si tu donnes un subdomain, tu peux essayer avec des tests jest tu verras. 

Idéalement du coup on merge les deux fonctions ensembles et ces deux fonctions gèrent les deux cas !

2023-04-13 11:13 UTC, fricoben commented on components/identities/actions/subdomainModal.tsx
> +  const encodedSubdomain: string = utils.encode(subdomain ?? "").toString(10);
Go alors

2023-04-13 11:13 UTC, fricoben commented on components/identities/actions/clickable/clickableDiscordIcon.tsx
> +      ?.getVerifierData(parseInt(tokenId), "discord")
Oui c'est mieux :)

2023-04-13 14:49 UTC, fricoben requested changes
Quelques petits trucs

2023-04-13 14:49 UTC, fricoben commented on components/braavos/braavosRenewal.tsx
> +// import { useEncoded } from "../../hooks/naming";
A delete

2023-04-13 14:49 UTC, fricoben commented on components/identities/actions/clickable/clickableDiscordIcon.tsx
> +  const { starknetIdNavigator } = useContext(StarknetIdJsContext);
Du coup tu as enlevé ton contexte qui wrappait toute l'app ?

2023-04-13 14:49 UTC, fricoben commented on hooks/naming.ts
> +  const [error, setError] = useState<string | undefined>(undefined);
`const [error, setError] = useState<string | undefined>();`

2023-04-13 14:49 UTC, fricoben commented on hooks/naming.ts
> +  const [error, setError] = useState<string | undefined>(undefined);
remove les `(undefined)`

2023-04-13 15:02 UTC, irisdv commented on components/identities/actions/clickable/clickableDiscordIcon.tsx
> +  const { starknetIdNavigator } = useContext(StarknetIdJsContext);
Non le Provider qui wrap toute l'app je suis obligée de le garder pour pouvoir accéder à `starknetIdNavigator` depuis n'importe quel component de l'app

2023-04-19 15:09 UTC, fricoben approved these changes

2023-04-26 16:23 UTC, merged