feat: integrate proof of personhood
starknet-id/app.starknet.id pull request #283
Opened 2023-06-26 14:05 UTC by irisdv

This PR closes #156

2023-06-27 14:54 UTC, fricoben requested changes
Quelques petites questions et on est good !

2023-06-27 14:54 UTC, fricoben commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +    (e: { info: any; state: any }) => {
Ce `e` n'est jamais utilisé non ? De plus pas de any :)

2023-06-27 14:54 UTC, fricoben commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +      .catch((err) => {
Chez moi j'ai `Parameter 'error' implicitly has an 'any' type.` Tu es sur que le catch marhce sur `execute` sachant que je ne pense pas que le execute throw une erreur

2023-06-27 14:54 UTC, fricoben commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +              Date.now(),
C'est le bon format ça ?

2023-06-27 14:59 UTC, irisdv commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +      .catch((err) => {
oui en effet, je l'ai enlevé

2023-06-27 15:12 UTC, irisdv commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +              Date.now(),
`Date.now()` me donne le timestamp en milliseconds, qui dans le contrat est comparé au timestamp récupéré avec `get_block_timestamp`. Tu penses qu'il faut que je l'envoie au format string plutôt ?

2023-06-27 15:13 UTC, irisdv commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +    (e: { info: any; state: any }) => {
du coup je l'ai enlevé !

2023-06-27 15:32 UTC, fricoben commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +              Date.now(),
Quand est ce que c'est comparé ? Tu es sur que le `get_block_timestamp` est en ms et pas en seconde ? Je crois que c'est seconde.

2023-06-27 15:39 UTC, Th0rgal commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +              Date.now(),
je crois aussi que c'est en secondes

2023-06-27 15:50 UTC, irisdv commented on components/identities/actions/clickable/clickablePersonhoodIcon.tsx
> +              Date.now(),
ah oui vous avez raison ce sont des secondes

2023-06-27 16:06 UTC, Th0rgal reviewed
besoin d'info sur le cache et  le timestamp

2023-06-27 16:06 UTC, Th0rgal commented on pages/api/anima/init_session.ts
> +      res.setHeader("cache-control", "max-age=30").status(200).json(result);
Ça risque pas de poser un pb de cache ? Le premier result sera toujours valable ? Si le gars recommence c'est peut-être parce que ça avait merdé ?

2023-06-28 14:23 UTC, fricoben approved these changes
LGTM

2023-06-28 14:23 UTC, merged