feat: add quantum leap discount
starknet-id/app.starknet.id pull request #352
Opened 2023-08-30 12:53 UTC by fricoben

This PR adds a potential Quantum Leap discount but also a way to create discounts easily with offer-upsell-checkout. 

I would like the review to be really focused on my architecture concerning the replicability of making a discount campaign and also the fact that I don't break important components (like the search bar for example). 

Thanks !

2023-09-12 16:47 UTC, irisdv requested changes
Your architecture looks good to me! The only case I see that would require more changes, would be if a discount is made on domains that have a length lower than 5 characters, it would require to update the code of the searchbar. If that could be the case one day, maybe you could update the search bar to pass the number of characters, instead of having `is5LettersOnly`.

I left a few comments in the code and I noticed that on mobile the register form with the discount is not responsive.

2023-09-12 16:47 UTC, irisdv commented on components/UI/searchBar.tsx
> +        message: "Only 5 letters domains for this discount",
Currently the message is also shown on the homepage when you search a domain

2023-09-12 16:47 UTC, irisdv commented on utils/discounts/quantumLeap.ts
> +    desc: "To celebrate the Quantum Leap, get your domain for just $1 and unlock a world of possibilities. Customize your On-chain StarkNet username, elevate your blockchain us er experience, and acc
there is a space in the middle of the word `user` in `your blockchain us er experience`

2023-09-12 16:47 UTC, irisdv commented on utils/discounts/quantumLeap.ts
> +} as const;
it's already declared as a const

2023-09-12 16:47 UTC, irisdv commented on components/discount/discountCheckoutScreen.tsx
> +          ]} // Second group is the special group for
I think there's a word missing at the end of the comment

2023-09-12 16:47 UTC, irisdv commented on utils/discounts/quantumLeap.ts
> +    duration: 81,
What's the unit of the duration ?

2023-09-13 08:03 UTC, fricoben commented on utils/discounts/quantumLeap.ts
> +    duration: 81,
Days, would be better to say it in the comment or in the name of the variable ?

2023-09-13 08:53 UTC, irisdv commented on utils/discounts/quantumLeap.ts
> +    duration: 81,
yes I think a comment would be good just in case someone new needs to create a new discount

2023-09-13 08:56 UTC, irisdv approved these changes
lgtm!

2023-09-13 12:37 UTC, merged