feat: identities page rework
starknet-id/app.starknet.id pull request #432
Opened 2023-10-08 08:41 UTC by Marchand-Nicolas

close: #428

2023-10-08 09:02 UTC, fricoben requested changes
<img width="742" alt="Capture d’écran 2023-10-08 à 10 59 12" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/24cc4438-5f26-448a-9ae9-ab034d04047a">

Size is different if domain or not, maybe you cann add the tokenId like `ID: XXX`

<img width="1374" alt="Capture d’écran 2023-10-08 à 10 55 06" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/7ce7db77-f422-47af-9588-b76c7dc087a8">

width too big

braavos external domains not showing as on the design (same for argent xplorer domain)

<img width="248" alt="Capture d’écran 2023-10-08 à 10 57 38" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/21fca480-2e4e-41fc-9a2b-a5f42d02507b">

We also have to change the skeleton that does not fit anymore (`identitiesSkeleton.tsx`)

2023-10-08 09:10 UTC, fricoben requested changes
Small change on the code side :)

2023-10-08 09:10 UTC, fricoben commented on pages/identities.tsx
>    const { account, address } = useAccount();
You can add the fix made on the identity page here pls ? https://github.com/starknet-id/app.starknet.id/pull/424/files#diff-2f396cbcb2a07a00a226255f1fc151a03e18ef663d722f673002730415d82f4dR20

You'll be able to close the issue #423

2023-10-08 10:46 UTC, Kevils requested changes
![Capture d’écran 2023-10-08 à 12 31 21](https://github.com/starknet-id/app.starknet.id/assets/144677881/f63a95fd-ef26-4ce0-bc65-aa1b989bdb5d)
- Vertical gap between Title and description : 16px
- Vertical gap between title/description and CTA : 48px
- Description width max 650px


![Capture d’écran 2023-10-08 à 12 37 47](https://github.com/starknet-id/app.starknet.id/assets/144677881/79cccfa4-f71b-4332-b527-a1418c19e8a3)
- Vertical and horizontal gap between card identities : 32px
- Vertical gap between identities gap and CTA : 48px

<img width="772" alt="image" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/9668de7d-27fe-4d8f-8b11-3755a0a18adf">
- Au hover, ajouter 2px de stroke Primary et passer du Small shadow au Large shadow


<img width="772" alt="Capture d’écran 2023-10-08 à 12 43 31" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/e62ee2b2-e38a-42e5-b9be-968c166b0761">
@fricoben Est-ce qu'on mettrait pas le numéro SID afin de card la même hauteur sur toutes les cards ?

<img width="797" alt="Capture d’écran 2023-10-08 à 12 45 14" src="https://github.com/starknet-id/app.starknet.id/assets/144677881/5ab494de-a019-4199-9b52-79a179c5cd95">
- Même retour que Benjamin sur les externals domains comme braavos et argent

2023-10-08 13:02 UTC, Kevils approved these changes

2023-10-08 13:03 UTC, Kevils requested changes
![Capture d’écran 2023-10-08 à 15 01 12](https://github.com/starknet-id/app.starknet.id/assets/144677881/ca6a8c48-5026-4cbe-9333-467efef43e2b)


- Fixé le width du CTA au responsive

2023-10-09 04:17 UTC, fricoben requested changes
On the front-end I have infinite loading when I'm not connected :) (easy to fix). 

Could we place this higher ? It's too much in the middle
<img width="194" alt="Capture d’écran 2023-10-09 à 11 15 55" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/e3c0d2f6-3ef3-426f-a2e6-0a6f3f8be306">

Could be cool to replace this by the image with the background (but without the border hover)

<img width="325" alt="Capture d’écran 2023-10-09 à 11 16 22" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/f8252346-1cc1-4594-9bd3-26a977be89f8">

We're almost done

2023-10-09 04:17 UTC, fricoben commented on components/identities/identitiesGalleryV1.tsx
> +          console.log(domainKind);
Delete the console.log :)

2023-10-09 05:49 UTC, Marchand-Nicolas commented
> On the front-end I have infinite loading when I'm not connected :) (easy to fix).

The issue come from the fix from here : https://github.com/starknet-id/app.starknet.id/pull/424/files#diff-2f396cbcb2a07a00a226255f1fc151a03e18ef663d722f673002730415d82f4dR20 I added. Is there something I missunderstood ? Because if I’m not wrong, in the fix it is explicitly written to load until the user connect its wallet

2023-10-09 08:26 UTC, Kevils approved these changes

2023-10-10 03:26 UTC, fricoben commented
<img width="827" alt="Capture d’écran 2023-10-10 à 10 26 09" src="https://github.com/starknet-id/app.starknet.id/assets/78437165/bf6ca5f2-5e05-40af-93f6-901fd038437d">

If I'm not connected I still have an infinite loading

2023-10-10 08:27 UTC, fricoben commented
close #423

2023-10-11 04:20 UTC, fricoben approved these changes
I fixed the connection problem, looks good to me

2023-10-11 04:21 UTC, merged