Feat/add renewal page
starknet-id/app.starknet.id pull request #433
Opened 2023-10-10 07:52 UTC by fricoben

close #394 

This page permits to addition of a renewal page that will permit anybody to renew their domains with a big multicall. Moreover, I changed some organization of the front-end with `write_confirmation` transactions to be more clean.

Here are the things to test before merging (done by @fricoben) : 
- [ ] Domain renew on modal 
- [ ] Multicall domain renewal (one year by default here)
- [ ] VAT transfer with multi-call domain renewal
- [ ] WriteVerifierData with twitter, discord, GitHub and POP

This PR can be an example of managing callData in the future. Ideally, we will move all the callData to the new folder created in this PR. 

We'll need 2 reviews here and it's very important to be cautious cause an error would create a lot of problems in production.

2023-10-10 16:09 UTC, Th0rgal commented on components/domains/renewal.tsx
> +              onUsResidentChange={() => setIsUsResident(!isUsResident)}
it's up to you to decide but when I update a state value using its existing value I prefer to use the function form, so setIsUsResident(prev => !prev) for example.

2023-10-10 16:26 UTC, Th0rgal requested changes
Issues:
- It is loading forever when I am not logged in.
- The page is `/[domain_variable].tsx` but doesn't use domain_variable

Suggestions:
- It could be nice to have a way to add new domains to the list, even if you don't own them (so that if I want to renew a domain for argent, partners or I one I deposited on a contract, I can do it)
- In the future having the option to toggle auto_renew would be great

2023-10-10 16:50 UTC, irisdv requested changes
I left a few comment in the code. Also if no domains are selected I think the button should be grey, otherwise it can send a tx with a transfer and approve of 0 :
<img width="709" alt="Capture d’écran 2023-10-10 à 18 32 09" src="https://github.com/starknet-id/app.starknet.id/assets/8224462/edbe9275-3e2a-4f0e-9213-a00086555cb5">

I don't understand what `domainToRenew` in the renewal page is used for. I tried with different domains and subdomains but it didn't have any effect.

I think the button in the identity page should also link to this page, because it's nicer but also because you can renew all your domains at once which is more practical than going through each identity. 

Why not show the expiration date as well in the renewal page ?

2023-10-10 16:50 UTC, irisdv commented on components/domains/renewal.tsx
> +                : "Register my domain"}
Replace by `Renew my domain` or even `domains`

2023-10-10 16:50 UTC, irisdv commented on components/domains/renewalDomainsBox.tsx
> +  return isLoading ? (
When the user is not connected, the domain box is always in loading mode, it's not really clear for the user that he's not connected

2023-10-12 08:28 UTC, fricoben commented
this also close #438

2023-10-12 08:48 UTC, irisdv approved these changes
lgtm!

2023-10-12 09:21 UTC, Th0rgal commented on components/UI/backButton.tsx
> +        color={onHover ? "#402d28bb" : theme.palette.secondary.main}
Using javascript for hover effects is a bad practice. I would suggest something like:
```css
.backButton {
  &:hover .arrowIcon {
    color: #402d28bb;
  }
  
  &:hover .backButtonLabel {
    /* Your hover styles for label */
  }
}
```

2023-10-12 11:26 UTC, Th0rgal approved these changes

2023-10-12 11:26 UTC, merged