feat: suggest more domains to buy
starknet-id/app.starknet.id pull request #554
Opened 2023-12-03 11:27 UTC by Marchand-Nicolas

close: #504

2023-12-03 17:46 UTC, fricoben requested changes
Front-end looks great congrats ! 

Some comments on the architecture: We always need to put utils functions appart from the component on itself. It permits us to test, the code to be clearer and more sustainable. 

The goal is to make the codebase organized to be easy to maintain overtime ! Let's change that and we will be all good.

2023-12-03 17:46 UTC, fricoben commented on components/domains/suggestedDomains.tsx
> +const generateSuggestedDomains = async (domain: string, contract: Contract) => {
This has to be in `stringService` and you can test also

2023-12-03 17:46 UTC, fricoben commented on components/domains/suggestedDomains.tsx
> +    (suggestedName) => `${suggestedName}.stark`
You can use the fonctions of `stringService` `getDomainWithStark` to do that. 

You can even have another function called `getDomainsWithStark` that will take an array and not a string

2023-12-03 17:46 UTC, fricoben commented on pages/search.tsx
> +        <SuggestedDomains domain={domain} />
You can add a skeleton here also ! Otherwise I have a strange thing when the website is charging

2023-12-03 17:46 UTC, fricoben commented on components/domains/suggestedDomains.tsx
> +const generateSuggestedNames: (name: string) => string[] = (name) => {
Same you should be in `stringservice` to be tested

2023-12-03 21:18 UTC, Marchand-Nicolas commented
Also fixed a bug on the front end (lines between table elements not being shown ![image](https://github.com/starknet-id/app.starknet.id/assets/60229704/eb8f8d4a-e79b-49d7-8602-482e5fb06950))

2023-12-04 14:26 UTC, Kevils requested changes
1 - Add hover effect
2 - Change "available" by "Available" 

![image](https://github.com/starknet-id/app.starknet.id/assets/144677881/666c384b-da77-4329-9b72-8336c6291f50)

2023-12-05 09:05 UTC, fricoben approved these changes
lgtm

2023-12-05 09:07 UTC, merged