feat: newsletter page
starknet-id/app.starknet.id pull request #681
Opened 2024-03-02 16:12 UTC by Marchand-Nicolas

2024-03-02 16:12 UTC, Marchand-Nicolas commented
API missing

2024-03-03 18:14 UTC, Marchand-Nicolas commented
Needs this before merging: https://github.com/starknet-id/api.sales.starknet.id/pull/7

2024-03-04 08:32 UTC, fricoben requested changes
LGTM except some wording I changed on vercel

2024-03-06 12:21 UTC, fricoben approved these changes
Code Lgtm, to merge when when we'll test and back-end will be in prod

2024-03-06 12:21 UTC, fricoben commented on pages/newsletter.tsx
> +    fetch(`${process.env.NEXT_PUBLIC_SALES_SERVER_LINK}/newsletter_subscribe`, {
Did you test that this back-end also triggers an add in the Mailerlite database ?

2024-03-07 08:59 UTC, Kevils requested changes
![image](https://github.com/starknet-id/app.starknet.id/assets/144677881/1755b376-c2e8-4ccf-a054-473d09fb4f6a)
![image](https://github.com/starknet-id/app.starknet.id/assets/144677881/e941081b-0035-4fd4-84de-b6b9ddcdbfba)

The email input, when focused, looks a bit strange. We could use the same background and text color as the domain form :)

2024-04-12 16:34 UTC, fricoben requested changes
I can subscribe even if my mail is not valid. 

We already have a function called `isValidEmail` in stringService for you to disable/enable the button when the email si valid.

2024-04-15 10:29 UTC, fricoben approved these changes
lgtm

2024-04-15 10:29 UTC, merged