ref: isStarkDomain with a regex
starknet-id/app.starknet.id pull request #75
Opened 2022-12-28 18:01 UTC by 0xBenaparte

Changement avec le regex

2022-12-28 18:12 UTC, Th0rgal commented
[1/4] Resolving packages...
--
19:03:30.333 | [2/4] Fetching packages...
19:04:01.814 | error An unexpected error occurred: "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz: Request failed \"522 undefined\"".

2022-12-29 17:39 UTC, 0xBenaparte commented
Je comprend pas l'erreur tu as plus d'infos sur l'erreur avec ton compte Vercel @Th0rgal ?

2023-01-02 16:02 UTC, Th0rgal requested changes
Est-ce que ce serait possible de construire charactersWithBigAlphabet en important les alphabets depuis le code source ? De sorte à ce que les tests restent corrects quand on décidera le big Alphabet

2023-01-11 07:53 UTC, Th0rgal approved these changes
Looks perfect to me

2023-01-11 15:18 UTC, merged