feat: smart option to reduce duration
starknet-id/app.starknet.id pull request #777
Opened 2024-05-13 16:41 UTC by Marchand-Nicolas

close: #773

2024-05-14 10:00 UTC, fricoben approved these changes
Doesn't work it creates several bugs :)

https://www.loom.com/share/cb1eb4e45c5849eeaffaa479ab888e36

2024-05-14 10:01 UTC, fricoben requested changes
Miss clicked my previous review it doesn't work https://github.com/starknet-id/app.starknet.id/pull/777#pullrequestreview-2054886919

2024-05-15 09:36 UTC, fricoben requested changes
Stll doesn't work for me. 

Please TEST before sending the PR, you have different case with different balances to test here.

https://www.loom.com/share/b2b8fa3296a54b6792cb8c1c4f0ebee3

## Cases to test
- [ ] Balance > discount > normal
- [ ] discount > balance > normal
- [ ] discount > normal > balance

2024-05-15 09:36 UTC, fricoben commented on components/domains/steps/upsellCard.tsx
> +  }, [displayedCurrency]);
Using displayed currency is not in my opinion a good way to do it. 

Imo you should simply say, that by default the discount is on but if `invalidBalance` is true then you put it off. Then you manage the manual change on top of that.

2024-05-15 15:44 UTC, irisdv approved these changes
lgtm in terms of code, I'll let @fricoben test it again

2024-05-15 16:12 UTC, fricoben approved these changes
lgtm

2024-05-15 16:12 UTC, merged