Adding a join-the-tribe page
starknet-id/app.starknet.id pull request #78
Opened 2023-01-02 09:48 UTC by Marchand-Nicolas

2023-01-07 10:33 UTC, 0xBenaparte requested changes

2023-01-07 10:33 UTC, fricoben commented on .gitignore
> +yarn.lock
à enlever de la PR

2023-01-07 10:33 UTC, fricoben commented on components/UI/hexagon.tsx
> +export default Hexagon;
Plutot à mettre dans le folder icon tu en penses quoi ?

2023-01-07 10:33 UTC, fricoben commented on components/UI/iconsComponents/icons/closeIcon.tsx
> +export default CloseIcon;
On a pas déjà de close icon ? Je crois que si mais je suis pas certain

2023-01-07 10:33 UTC, fricoben commented on components/UI/navbar.tsx
> +              </Link>
A rajouter aussi dans le responsive

2023-01-07 10:33 UTC, fricoben commented on components/UI/textCopy.tsx
> +  className?: string;
On ne passe jamais les classname en props ;). Pourquoi tu fais ça comme cela ici 🤟 ?

2023-01-07 10:33 UTC, fricoben commented on components/UI/textCopy.tsx
> +  return <div className={[styles.container, "relative", className].join(' ')}>
Un peu compliqué pour faire du CSS je suis sur qu'il y a une solution plus simple

2023-01-07 10:33 UTC, fricoben commented on components/UI/textCopy.tsx
> +      }, 1000);
Bien ça avec le temps

2023-01-07 10:33 UTC, fricoben commented on components/tribe/memberHoverMenu.tsx
> +import styles2 from "../../styles/jointhetribe.module.css";
Renommer en simplement `styles`

2023-01-07 10:33 UTC, fricoben commented on components/tribe/memberHoverMenu.tsx
> +const MemberHoverMenu: FunctionComponent<any> = ({ id, member, style={} }) => {
Je vois pq tu as mis le nom du css en style maintenant mais il faut changer ce naming là car il est pas assez expressif à mon sens + on ne doit pas passer les styles en props normalement + Pas de `any` dans les types, ici tu créer un type spécial pour le composant comme tu as fais avant

Tu peux m'expliquer pourquoi tu le fais ici stp ? 🤟

2023-01-07 10:33 UTC, fricoben commented on components/tribe/searchMembers.tsx
> +  hoverMember: (e: any, index:number, member: any) => void;
Pas de `any`, à toi de voir quel type est nécéssaire ici. Tu peux passer ta souris sur l'élément pour le voir.

2023-01-07 10:33 UTC, fricoben commented on components/tribe/memberHoverMenu.tsx
> +  const parseTwitterDescription = (description: string, entities: any) => {
Pas deux composants dans le meme composant. 

Il faut recréer un fichier + pas de `any` encore y'en a pas mal dans ce petit composant.

Tous le but de typescript c'est de pas mettre de any et de typer ce qui arrive. Meme si ça te parait logique vu que toi tu sais, le mec qui relit dans 6 mois quand l'app aura évolué il sera perdu.

2023-01-07 10:33 UTC, fricoben commented on components/tribe/searchMembers.tsx
> +  const [followers, setFollowers] = useState<any>([])
any encore ;). 

Je te laisserai changer les autres je vais pas me répéter à chaque fois tu as compris l'idée. 

Si kle type n'existe pas directement dans typescript. Créer ton propre type ;). Si tu le réutilises à travers plusieurs fichiers tu peux le mettre dans `frontTypes.ts` ou `backTypes.ts`

2023-01-07 10:33 UTC, fricoben commented on components/tribe/searchMembers.tsx
> +  const [tab, setTab] = useState<'followers' | 'following'>('followers')
Pour ce genre de chose tu fait un type ou un enum aussi ;)

2023-01-07 10:33 UTC, fricoben commented on components/tribe/searchMembers.tsx
> +  const [user, setUser] = useState(undefined)
useState() fonctionne bien et rajoute les types dans les useState ;)

2023-01-07 10:33 UTC, fricoben commented on pages/api/indexer/stats/count_club_domains.ts
> +      }
ce sont des anciens changements ici tu devrais rebase ta branche testnet et mainnet avec celle actuelle ;)

2023-01-07 10:33 UTC, fricoben commented on pages/jointhetribe.tsx
> +    if (code) getTwitterToken();
espace ici pour que ça soit plus facile à lire (entre le if et les const)

2023-01-07 10:33 UTC, fricoben commented on pages/jointhetribe.tsx
> +  useEffect(() => {
Pourquoi tu fais une useEffect ? Tu veux passer que quand la page se charge ?

2023-01-07 10:33 UTC, 0xBenaparte commented on components/tribe/claim.tsx
> +  useEffect(() => {
ça je changerai surement la manière de faire en m'inspirant de ce que tu as fais

2023-01-08 10:02 UTC, Marchand-Nicolas commented on components/UI/iconsComponents/icons/closeIcon.tsx
> +export default CloseIcon;
![image](https://user-images.githubusercontent.com/60229704/211190132-fbadb7b9-c006-4a6e-b338-c3441e961edf.png)
Après avoir cherché j'en ai trouvé une dans le composant wallet, mais aucune appartenant à son propre composant

2023-01-08 10:09 UTC, Marchand-Nicolas commented on components/UI/textCopy.tsx
> +  className?: string;
Je pensais que c'était mieux que d'englober le composant dans une div et de mettre la classname à celle-ci. Je vais faire cela, à moins qu'il y ait mieux ?

2023-01-08 13:49 UTC, Marchand-Nicolas commented on pages/jointhetribe.tsx
> +  useEffect(() => {
![image](https://user-images.githubusercontent.com/60229704/211199553-c824fb93-0603-4a33-b15d-dbf015670d99.png)
Comme le code travail sur l'URL, je me dis que ya pas besoins d'executer ce code à chaque render, cela suffit de le faire quand la page change (et donc que l'URL change)

2023-01-09 09:14 UTC, 0xBenaparte commented on components/UI/iconsComponents/icons/closeIcon.tsx
> +export default CloseIcon;
Ok bien vu, tu peux remplacer celui du composant wallet par le tiens alors normalement ;). GG !

2023-01-09 09:33 UTC, 0xBenaparte commented
Je recheck ta PR la. 

Y'a encore pas mal de chose à changer notamment les `any`.

Pour voir tous ceux qu'il y a à changer tu peux faire `npm run build` et regarder ou sont les warnings (en + de ça la PR ne build pas à l'heure actuelle). 

De mon coté je vais faire quelque changements cosmétiques pour coller au nouveau design auquel je pensais je ferai une PR pour cela entre ajd et demain.

2023-01-09 09:36 UTC, 0xBenaparte commented on public/datas/famousTribeMembers.json
> +    "name": "th0rgal.stark",
Imagine la personne change de nom ou de description on est niqué ? Le mieux serait de le GET une fois par semaine par exemple et le mettre derrière dans le back-end de next js tu en penses quoi ? Tu as une autre idée ?

2023-01-09 09:40 UTC, 0xBenaparte commented on pages/jointhetribe.tsx
> +  const hoverMember = (e: React.MouseEvent, index: number, member: Member) => {
ça c'est un composant à part, l'objectif est de faire des fichiers les plus court que possible pour améliorer la lisibilité du code. tu peux mettre dans `/components/tribe`

2023-01-09 09:51 UTC, 0xBenaparte commented on pages/jointhetribe.tsx
> +            <div className={["ml-4", styles2.center].join(' ')}>
Ici tu as parfois des `.join(" ")` ou comme ça `.join(' ')`. 

Il faut harmoniser et garder soit l'un soit l'autre. Nous on utiliser "", tu peux utiliser un outil d'extension VS code comme prettier pour le faire automatiquement. (je vais bientot rajouter ça dans le linter)

2023-01-09 10:11 UTC, 0xBenaparte commented on utils/cookies.ts
> +  let expires = "expires="+ d.toUTCString();
Pas de let. Tu as des problèmes de linter ici. 

Tu dois utiliser notre linter (ça ne passe pas sur mon vs code par exemple ça).

<img width="589" alt="Capture d’écran 2023-01-09 à 11 10 29" src="https://user-images.githubusercontent.com/78437165/211284586-dcd24f1c-6e19-4627-b437-3d31a8b7eb38.png">

Dis moi si tu n'arrives pas à le faire je ferai avec toi mais normalement tout se passe dans `.eslintrc.json`

2023-01-09 10:12 UTC, fricoben commented on utils/domain_string_to_felt.ts
> +export default function domainStringToFelt(domain: string) {
Existe déjà normalement

2023-01-09 17:38 UTC, Marchand-Nicolas commented on pages/jointhetribe.tsx
> +            <div className={["ml-4", styles2.center].join(' ')}>
Plutôt {"ml-4 " + styles2.center } (avec un espace) je suppose. Je vais switch vers ça. Sinon il est aussi possible de faire 
comme ça 
![image](https://user-images.githubusercontent.com/60229704/211371678-684be59b-e53b-4c52-9aef-92467a927e35.png).
Dis moi ce que tu préfères

2023-01-09 17:42 UTC, Marchand-Nicolas commented on public/datas/famousTribeMembers.json
> +    "name": "th0rgal.stark",
Tu as raison, je vais implémenter ça. Du coup le json sera composé d'un array rempli d'IDs.

2023-01-09 17:43 UTC, Marchand-Nicolas commented on utils/domain_string_to_felt.ts
> +export default function domainStringToFelt(domain: string) {
Je n'ai pas trouvé le fichier. Il se situe où ?

2023-01-11 17:30 UTC, closed without merging